"""API routers. Each module exposes a `router` attribute mounted in main.py."""

from app.routers import (
    ai,
    attachments,
    auth,
    authors,
    contracts,
    dashboard,
    editorial_notes,
    exports,
    health,
    manuscripts,
    meta,
    production_items,
    production_records,
    reviews,
    search,
    workflow,
    workflow_events,
)

ALL_ROUTERS = (
    health,
    meta,
    auth,
    dashboard,
    search,
    authors,
    manuscripts,
    reviews,
    workflow,
    workflow_events,
    contracts,
    production_items,
    production_records,
    editorial_notes,
    attachments,
    exports,
    ai,
)

__all__ = [
    "ALL_ROUTERS",
    "ai",
    "attachments",
    "auth",
    "authors",
    "contracts",
    "dashboard",
    "editorial_notes",
    "exports",
    "health",
    "manuscripts",
    "meta",
    "production_items",
    "production_records",
    "reviews",
    "search",
    "workflow",
    "workflow_events",
]
